package com.tmane.springbootmvcdemo.enums;

public enum Sector {
    INFORMATION_TECHNOLOGY,
    FINANCE_AND_BANKING,
    HEALTHCARE_AND_LIFE_SCIENCES,
    ENERGY_AND_UTILITIES,
    MANUFACTURING,
    RETAIL_AND_ECOMMERCE,
    REAL_ESTATE_AND_CONSTRUCTION,
    TRANSPORTATION_AND_LOGISTICS,
    FOOD_AND_BEVERAGES,
    ENTERTAINMENT_AND_MEDIA,
    DFAULT_SECTOR
}
